#!/usr/bin/env python3
"""
Builds a plain-text/markdown "Profile Brief" from the same vault sources as
build_cv.py. This isn't a file to publish anywhere -- it's the reference you
(or a future Claude-in-VS-Code session) check against when updating LinkedIn
or Seek by hand, so the wording, dates and titles never drift out of sync
with the CV or with each other. When you update LinkedIn/Seek, copy FROM
this file; when the underlying facts or positioning change, regenerate this
file -- never hand-edit it directly.

Usage: python build_profile_brief.py [--output ../output/profile-brief.md]
"""
import argparse
import datetime
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent / "lib"))
import load_vault as vault  # noqa: E402


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="../output/profile-brief.md")
    args = parser.parse_args()

    cv_dir = Path(__file__).parent
    vault_dir = cv_dir.parent / "vault"
    config = json.loads((cv_dir / "config.json").read_text(encoding="utf-8"))

    profile = vault.load_profile(vault_dir)
    positioning = vault.load_positioning(vault_dir)
    employment = vault.load_employment(vault_dir, config["employmentOrder"])
    highlights = vault.load_project_highlights(vault_dir, config["selectedProjects"])

    lines = []

    def h(title):
        lines.append(f"\n## {title}\n")

    lines.append(f"# Profile Brief — generated {datetime.date.today().isoformat()}")
    lines.append(
        "\nSource of truth for LinkedIn and Seek text. Copy FROM here when "
        "updating either profile. Do not edit this file directly -- it's "
        "regenerated from vault/00-Facts and vault/02-Positioning."
    )

    h("Name / Headline")
    lines.append(profile["name"])
    lines.append(positioning["headline"])
    lines.append(
        "(LinkedIn headline field is capped at 220 characters -- trim if "
        "needed, but don't change the substance without updating "
        "vault/02-Positioning/CV-Positioning.md first.)"
    )

    h("Contact")
    lines.append(f"{profile['email']} | {profile['phone']} | {profile['linkedin']} | {profile['location']}")

    h("Summary / About")
    lines.append(positioning["summary"])
    lines.append(f"\n{positioning['quote']}")
    lines.append(f"\nTarget roles: {positioning['target_roles']}")

    h("Career History (use identical dates/titles across LinkedIn, Seek and the CV)")
    for job in employment:
        date_loc = ", ".join(x for x in [job.get("period"), job.get("location")] if x)
        suffix = f"  ({date_loc})" if date_loc else ""
        lines.append(f"\n**{job['display_label']}**{suffix}")
        if job["type"] == "bullet-list":
            for b in vault.bullets_from(job["body"]):
                lines.append(f"- {b}")
        else:
            lines.append(job["body"])

    h("Selected Projects (for LinkedIn's Featured/Projects section or Seek's summary)")
    for hl in highlights:
        lines.append(f"- {hl['text']}")

    h("Skills / Domain Expertise")
    lines.append(positioning["domain_expertise"])
    lines.append(
        "\n(LinkedIn's Skills section takes individual tags, not a "
        "sentence -- split the list above into separate skill entries "
        "there, pinning the top 3 that match the headline.)"
    )

    h("Core Competencies")
    for c in positioning["core_competencies"]:
        lines.append(f"- {c}")

    h("Credentials")
    for c in profile["credentials"]:
        lines.append(f"- {c}")

    h("Education")
    for e in profile["education"]:
        lines.append(f"- {e}")

    output_path = (cv_dir / args.output).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
